# File: azure-pipelines\pull-request-validation\common.yml
# Description: Assemble and run unit test
name: $(date:yyyyMMdd)$(rev:.r)


trigger:
  branches:
    include:
    - dev
    - master
    - release/*
  batch: True

resources:
  repositories:
  - repository: self
    type: git
    ref: dev

pool:
  name: Hosted Windows 2019 with VS2019

jobs:
- job: build_test
  displayName: Build & Test
  cancelTimeoutInMinutes: 1
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: ../templates/steps/automation-cert.yml
  - task: CmdLine@1
    displayName: Set Office MVN Access Token in Environment
    inputs:
      filename: echo
      arguments: '##vso[task.setvariable variable=ENV_VSTS_MVN_ANDROIDCOMMON_ACCESSTOKEN]$(System.AccessToken)'
  - task: Gradle@3
    name: Gradle3   
    displayName: Assemble Local
    inputs:
      javaHomeSelection: JDKVersion
      jdkVersionOption: "1.11"
      tasks: clean common:assembleLocal
      publishJUnitResults: false
      jdkArchitecture: x64
      sqAnalysisEnabled: false
  - task: Gradle@2
    displayName: Run Unit tests
    inputs:
      javaHomeSelection: JDKVersion
      jdkVersionOption: "1.11"
      tasks: common:testLocalDebugUnitTest

- job: spotbugs
  displayName: SpotBugs
  cancelTimeoutInMinutes: 1
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: ../templates/steps/spotbugs.yml
    parameters:
      project: common
- job: lint
  displayName: Lint
  cancelTimeoutInMinutes: 1
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - task: CmdLine@1
    displayName: Set Office MVN Access Token in Environment
    inputs:
      filename: echo
      arguments: '##vso[task.setvariable variable=ENV_VSTS_MVN_ANDROIDCOMMON_ACCESSTOKEN]$(System.AccessToken)'
  - task: Gradle@3
    displayName: Lint
    inputs:
      tasks: clean common:lintLocalDebug
      publishJUnitResults: false
- job: codeql
  displayName: CodeQL
  cancelTimeoutInMinutes: 1
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - task: CmdLine@1
    displayName: Set Office MVN Access Token in Environment
    inputs:
      filename: echo
      arguments: '##vso[task.setvariable variable=ENV_VSTS_MVN_ANDROIDCOMMON_ACCESSTOKEN]$(System.AccessToken)'
  # https://semmleportal.azurewebsites.net/codeql/guardian
  - task: Semmle@1
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      sourceCodeDirectory: '$(Build.SourcesDirectory)'
      language: 'java'
      buildCommandsString: 'gradlew.bat clean common:assembleLocal'
      querySuite: 'Recommended'
      timeout: '1800'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish code analysis artifacts'
    inputs:
      targetPath: '$(Build.SourcesDirectory)\build\outputs\'
      ArtifactName: 'outputs'
    condition: failed()
...
